### ISSUE TITLE
ain function ??

### ISSUE THREAD

**Issue by eastchun** [terryoo/AINDNet#4]
In your following code, def ain():
```
noisemap_beta = tf.layers.conv2d(tmp, channels, [3, 3],                                          kernel_initializer=tf.contrib.layers.variance_scaling_initializer(0.02),
                                          padding='same',
                                          name='conv_beta')
```
'tmp' needs to be changed into 'noisemap_gamma' ??
Otherwise, 'noisemap_gamma' and 'noisemap_beta' are the same...

**Comment by terryoo** [comment]
We find that the parallel structure achieves better performance than the sequential structure in ain module.
The released code is the parallel structure, which is slightly different from paper.
We will close the issue.
